import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: { default: "Next js default", template: "%s | Next" }, 
  description: "Generated by create next app",
};

// default title will be applied to all pages without title metadata
// template will look like this "%s (some text)" %s will insert the title from the child elements and add the other string
// absoulte will ignore all of the titles that are set in the  any element and will set it to this  string

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>this will be in all pages</header>
        <section>{children}</section>
      </body>
    </html>
  );
}
